name: Test

'on':
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 6"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - 'pypy3-3.8'
        pip-version:
          - '>=10,<18'
          - '>=18,<19'
          - '>=19,<20'
          - '>=20,<21'
          - '>=21,<22'
          - '>=22,<23'

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PIP
        run: |
          python -m pip --disable-pip-version-check install "pip${{ matrix.pip-version }}"
          pip --disable-pip-version-check --version

      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - name: Install
        run: |
          pip --disable-pip-version-check install -e .
          pip --disable-pip-version-check freeze

      - name: Test
        run: envrpt

