name: Test

'on':
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 6"

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - pypy3
        pip-version:
          # - '>=10,<18'
          - '>=18,<19'
          - '>=19,<20'
          - '>=20,<21'

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PIP
        run: python -m pip --disable-pip-version-check install "pip${{ matrix.pip-version }}"

      - name: Install Poetry
        uses: jayclassless/setup-poetry-action@v1

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install
        run: |
          make setup
          make env

      - name: Test
        run: envrpt

